### ISSUE TITLE
Update the Sample-App to use the latest SDK version

### ISSUE THREAD

**Issue by Moes81** [dolphin-technologies/MOVE-App-Android#1]
Hello!
I'm currently evaluating the SDK. But unfortunately the sample app still uses SDK version `2.1.0.67`. So I had to upgrade the app at some places to work correctly with the latest SDK version (currently: `2.3.1.67`).
Would you mind updating the samples to use the latest version of the SDK so potential customers have a smooth start into your product?

Regards
Andreas

P.S. You might want to mention the renaming of `AssistanceCallState` to `MoveAssistanceCallStatus` in the change logs.

**Comment by kopfnick** [comment]
@Moes81 Thank you for bringing this to our attention - we are working on releasing updated sample apps code in the next 1 or 2 sprints!

**Comment by kopfnick** [comment]
@Moes81 The updated apps are now available :)
